### ISSUE TITLE
Add usage documentation

### ISSUE THREAD

**Issue by fuerst** [xrav3nz/discourse-wellfed#3]
Can you please add a short documentation for how to use the plugin once installed? I wasn't able to figure it out by myself - using Discourse 2.3.

**Comment by xrav3nz** [comment]
Hi @fuerst, very sorry about the late response, I wasn't watching the repo.

I have added instructions on how to install and set up the plugin in eb411ec, let me know if this clears it up. Thanks for checking out the plugin!
